fix(android sanitize): Support value in String and Integer
la-haus/iterable-flutter pull request #17
Opened 2021-09-29 16:03 UTC by Santi92

what this PR:

- Homogeneity of data types
- Parser  String numeric to Integer 

## Issues encountered with iterable android SDK

It happens that when Iterable push arrives, it saves them in a map with String type key and String type Value, this makes it inconsistent with IOS.

I show where this is done in Iterable api:

**terableFirebaseMessagingService**
https://github.com/Iterable/iterable-android-sdk/blob/b7815ca6a02a6fb3fe14d160aa539e563ca1180e/iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java#L39-57

**IterableNotificationHelper**
https://github.com/Iterable/iterable-android-sdk/blob/b7815ca6a02a6fb3fe14d160aa539e563ca1180e/iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java#L84

# Unit test
It is only tested that numeric String can be correctly transformed to integers and ensure that the map of values is sent correctly, this is tested since it is important logic for the homogeneity between  `IOS`

**Nota:** No test is carried out with the Bundle type data since it is typical of Android and the tests are complicated, with the aforementioned tests will be carried out from a map.

2021-09-29 20:31 UTC, cdmunoz requested changes
Nice!! 😎  👌🏻 

I left you a couple of comments

2021-09-29 20:31 UTC, cdmunoz commented on android/src/main/kotlin/com/lahaus/iterable_flutter/NotificationParser.kt
> +
I think this blank line could be removed

2021-09-29 20:31 UTC, cdmunoz commented on android/src/main/kotlin/com/lahaus/iterable_flutter/NotificationParser.kt
> +
I think this blank line could be removed

2021-09-29 20:31 UTC, cdmunoz commented on android/src/main/kotlin/com/lahaus/iterable_flutter/NotificationParser.kt
> +        }else{
Did you apply a style format? 🙈

2021-09-29 20:31 UTC, cdmunoz commented on android/src/main/kotlin/com/lahaus/iterable_flutter/NotificationParser.kt
> +}
I'm not sure if this should be the best approach, probably something like (I'm not sure if it compiles well, but I feel like (consider) putting logic into a `catch` is not a good practice)

```kotlin
when(myString) {
    is String -> myString.toInt()
    else -> this
}
```

Or doing the logic taking into consideration this stdlib extension:
[https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-int-or-null.html](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-int-or-null.html)

2021-09-29 20:31 UTC, cdmunoz commented on android/src/test/java/com/lahaus/iterable_flutter/MockData.kt
> +class MockData {
Shouldn't it be within `test` package?

2021-09-29 20:31 UTC, cdmunoz commented on android/src/test/java/com/lahaus/iterable_flutter/NotificationParserTest.kt
> +class NotificationParserTest {
Shouldn't it be within `test` package?

2021-09-29 20:46 UTC, juansoos requested changes
Great job 🚀 I agree with @cdmunoz comments, taking the considerations it would be ok for me

2021-09-29 21:16 UTC, danielgomezrico requested changes
Did we change the result map format?

In swift side we have the "title" and "additionalData" structure, but it looks like we do not have that structure here anymore.

Swift code: https://github.com/la-haus/iterable-flutter/blob/master/ios/Classes/SwiftIterableFlutterPlugin.swift#L109-L113

2021-09-29 22:55 UTC, Santi92 commented
> Did we change the result map format?
> 
> In swift side we have the "title" and "additionalData" structure, but it looks like we do not have that structure here anymore.
> 
> Swift code: https://github.com/la-haus/iterable-flutter/blob/master/ios/Classes/SwiftIterableFlutterPlugin.swift#L109-L113

@danielgomezrico  Yes, here this is. 

https://github.com/la-haus/iterable-flutter/blob/be04481c6f1b914775c37d9bb5cf8f6cb991aa0b/android/src/main/kotlin/com/lahaus/iterable_flutter/NotificationParser.kt#L31-L38

2021-09-29 23:15 UTC, danielgomezrico approved these changes
Awesome 🪨 🚀

2021-09-30 00:06 UTC, cdmunoz approved these changes
Such a great job! 👏🏻  💪🏻

2021-09-30 00:25 UTC, juansoos approved these changes
Goooo! 🚀

2021-09-30 14:05 UTC, merged