chore(Readme): Add comments about web in readme and cleanup the steps
la-haus/iterable-flutter pull request #26
Opened 2021-10-16 17:04 UTC by danielgomezrico

This will show the readme:

- What's the current status of the web 
- How to add this library as a dependency from github
- Cleanup the steps to use the library
- Add a warning saying that this is in alpha (because https://github.com/la-haus/iterable-flutter/issues/23 asked to know whats the status of this and it will let this clear)

2021-10-16 21:13 UTC, cdmunoz requested changes
Great!! 💯 

I left you a small comment to complete the step by step documentation. 🤓

2021-10-16 21:13 UTC, cdmunoz commented on README.md
> +
I'd add a `6.` step to do the signOut:

`6. Call `signOut` to unregister the device for push notifications, then the device will be removed from active devices to receive them.`

2021-10-19 14:45 UTC, danielgomezrico commented on README.md
> +
@cdmunoz I didn't want to add that because we dont have `signOut` implementation on iOS, is that already done?

2021-10-19 14:47 UTC, Santi92 approved these changes
Good Job 🚀

2021-10-19 14:48 UTC, juansoos approved these changes
Great! 💯

2021-10-19 14:53 UTC, cdmunoz commented on README.md
> +
ahhhggg ... you're right @danielgomezrico! I thought it was ... it should be ... probably we could add it, because it's just calling `logoutUser` and that's all ... it means that a new version of the plugin should be released but it's our choice

2021-10-21 11:37 UTC, danielgomezrico commented on README.md
> +
I think that since is not in the roadmap at the moment, it is not required to add it

2021-10-21 15:26 UTC, cdmunoz approved these changes
Osom! 🧐

2021-10-22 11:52 UTC, merged