feat(updateUser): Implementing updateUser SDK function
la-haus/iterable-flutter pull request #31
Opened 2021-10-25 22:49 UTC by Gabriel-Azevedo

This PR: Implementing updateUser SDK function

2021-10-25 23:51 UTC, danielgomezrico requested changes
Awesome job, thanks for the contribution, I left one minor question

2021-10-25 23:51 UTC, danielgomezrico commented on android/src/main/kotlin/com/lahaus/iterable_flutter/IterableFlutterPlugin.kt
> +import org.json.JSONException
Do you need this import? I see that you only use JSONObject

2021-10-25 23:59 UTC, cdmunoz commented on example/lib/main.dart
> +            ),
I see that this can all fit in one line, and it's not affecting the aesthetics of params! 😃

2021-10-26 00:00 UTC, cdmunoz commented on example/lib/main.dart
> +            ),
I see that this can all fit in one line, and it's not affecting the aesthetics of params! 😃

2021-10-26 00:02 UTC, cdmunoz approved these changes
LGTM! 🚀  Thanks for contributing 💪🏻 

I left you a couple of comments, that are not affecting the PR core, but just a small detail in the sample app.

2021-10-26 13:53 UTC, Gabriel-Azevedo commented on android/src/main/kotlin/com/lahaus/iterable_flutter/IterableFlutterPlugin.kt
> +import org.json.JSONException
I thought I would, but ended up not using it. It's removed.

2021-10-26 13:54 UTC, Gabriel-Azevedo commented on example/lib/main.dart
> +            ),
Fixed. Linter habits haha

2021-10-26 13:54 UTC, Gabriel-Azevedo commented on example/lib/main.dart
> +            ),
Fixed. Linter habits haha

2021-10-26 14:54 UTC, danielgomezrico approved these changes
Awesome, LGTM

2021-10-27 22:43 UTC, merged