feat(registerForPush) Implementing registerForPush on iOS
la-haus/iterable-flutter pull request #32
Opened 2021-10-29 21:33 UTC by Gabriel-Azevedo

## What
Implementing (unused) registerForPush function on iOS

## Why
Currently, the registerForPush function is called automatically on `didFinishLaunchingWithOptions` which isn't always the best place. Most of the time you want to ask for permission during a custom flow, so my proposal is to stop calling that function automatically and leave it up to the developer to call it at the appropriate time.

## BREAKING CHANGE
Any app that lets the registerForPush function be called automatically would need to call it manually now.

2021-10-29 23:35 UTC, cdmunoz approved these changes
LGTM 🚀

2021-10-29 23:37 UTC, danielgomezrico commented
@Gabriel-Azevedo in the CI we see that in the last PR you included some tests that have some issues, can you please fix them?

Errors:
```bash
  error • The named parameter 'params' is required, but there's no corresponding argument • test/iterable_flutter_test.dart:139:27 • missing_required_argument
  error • Too many positional arguments: 0 expected, but 1 found • test/iterable_flutter_test.dart:139:38 • extra_positional_arguments_could_be_named
  error • Undefined name 'params' • test/iterable_flutter_test.dart:139:38 • undefined_identifier
  error • Undefined name 'params' • test/iterable_flutter_test.dart:141:45 • undefined_identifier
```

2021-10-29 23:38 UTC, danielgomezrico approved these changes
Good job

2021-10-29 23:39 UTC, cdmunoz requested changes
I see the CI is failing running the tests ... can you check pls and fix them?

2021-10-29 23:39 UTC, danielgomezrico requested changes
🤓

2021-10-30 17:58 UTC, danielgomezrico approved these changes
Thanks for the feature, good job

2021-10-30 21:10 UTC, cdmunoz approved these changes
Such a great job! 💪🏻  🍄

2021-10-30 21:11 UTC, merged