Add support for data fields when tracking events.
la-haus/iterable-flutter pull request #53
Opened 2022-05-18 19:47 UTC by masterwok

This pull request adds support for data fields when tracking events.

2022-05-18 19:55 UTC, danielgomezrico requested changes
Thanks for this contribution! 

I do see that you reindented a lot of files, please be careful with that because that shows a lot of changes, but you were changing just a small part of it.

2022-05-18 20:09 UTC, cdmunoz reviewed
Thanks for the contribution! 👌🏻 

Also, it'd be important that in the description of the PR this contains more details and we could see the current behavior and the expected behavior with the proposed change.
This would help us to visualize the impact of the change.

2022-05-18 20:23 UTC, masterwok commented
Thank you for your fedback @cdmunoz and @danielgomezrico. I've updated the PR description to include more information. Sorry about the white-space diffs; main changes in plugin are contained within "track" event handling code.

2022-05-19 17:27 UTC, danielgomezrico commented
@masterwok sorry to be picky about this, but I see also other naming changes and things like that, is there any possibility that you revert all of that and just submit your feature change?

2022-05-24 14:58 UTC, masterwok commented
@danielgomezrico 

Can you please be a little more specific with what you would like reverted? I'm not sure what naming changes you're referring to.

2022-06-03 16:44 UTC, danielgomezrico commented
@masterwok can you restore the old indentation to see what are your changes please?

2022-12-23 16:44 UTC, danielgomezrico commented
👍🏻 Thanks @masterwok for the work, in this PR https://github.com/la-haus/iterable-flutter/pull/61 the issue got covered

2022-12-23 16:44 UTC, closed without merging